import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Devwer 🕵️‍♀️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Dev</h1>
      </main>
      <style jsx>
        {`
          main {
            font-size: 62.5%;
            max-width: 1200px;
          }
          h1 {
            font-size: 4rem;
            margin: 0;
            text-align: center;
          }
        `}
      </style>
    </div>
  );
}
