import Head from "next/head";
// import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import AppLayout from "../ui";

export default function Home() {
  return (
    <>
      <Head>
        <title>Devwer 🕵️‍♀️</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <h1>Dev</h1>
        <Link href="/timeline">
          <a>Timeline</a>
        </Link>
      </AppLayout>
    </>
  );
}
